PACMAN8 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ     ZZZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM       MMNM      MMMM      MMMM      MMMM       MMM       NNM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN     MMMMMM    NMMMMM    MMMMMM    MMMMMM     MMNMM     NMMMM
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM       MNMN      MNNM      MNMM      NMMM       MMM       MNM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN7 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ    ZZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM       MMNM      MMMM      MMMM      MMMM       MMM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN     MMMMMM    NMMMMM    MMMMMM    MMMMMM     MMNMM
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM       MNMN      MNNM      MNMM      NMMM       MMM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN6 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ    ZZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM       MMNM      MMMM      MMMM      MMMM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN     MMMMMM    NMMMMM    MMMMMM    MMMMMM
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM       MNMN      MNNM      MNMM      NMMM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN5 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ    ZZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM       MMNM      MMMM      MMMM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN     MMMMMM    NMMMMM    MMMMMM
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM       MNMN      MNNM      MNMM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN4 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ    ZZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM       MMNM      MMMM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN     MMMMMM    NMMMMM
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM       MNMN      MNNM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN3 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ    ZZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM       MMNM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN     MMMMMM
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM       MNMN
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN2 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZZ    ZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM       MNMM
ZZZZZZZZZZZZZZZ?      MMNMMM     MMNMNN
ZZZZZZZZZZZZZZZOOI     MMMM       MMNM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN1 =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZZ     ZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ
ZZZZZZZZZZZZZZZZOI     NMMM
ZZZZZZZZZZZZZZZ?      MMNMMM
ZZZZZZZZZZZZZZZOOI     MMMM
ZZZZZZZZZZZZZZZZZ$Z:
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ     ZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ                     ------------------
ZZZZZZZZZZZZZZZZOI                            THE END!
ZZZZZZZZZZZZZZZ?                              YOU LOST
ZZZZZZZZZZZZZZZOOI                                =(
ZZZZZZZZZZZZZZZZZ$Z:                      -----------------
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN

PACMAN_WIN =
<<-PACMAN
    OZZOZZZZO$ZZZO
,OZZZZZZZZZZZZZ$Z$ZOI
ZOOZZZZZZZZZZZZZZZZZ$ZO
8ZZZ$ZZZZZZZ     ZZZZO$Z$
ZZZZZZZZZZZZZZZZZZZZZZ$ZI
O$ZZZZZZZZZZZZZZZZZZZZZ=
ZZZZZZZZZZZZZZZZZ$$Z$O
ZZZZZZZZZZZZZZZZZZOZ                     ------------------
ZZZZZZZZZZZZZZZZOI                            CONGRATS!
ZZZZZZZZZZZZZZZ?                              YOU WON!!!!
ZZZZZZZZZZZZZZZOOI                                =D
ZZZZZZZZZZZZZZZZZ$Z:                      -----------------
ZZZZZZZZZZZZZZZZZZZZZO
ZZZZZZZZZZZZZZZZZZZZZ$Z
ZZZZZZZZZZZZZZZZZZZZZZZZ
OZZZZZZZZZZZZZZZZZZZZZ$Z8
Z$Z$ZZZZZZZZZZZZZZZZO$Z
O$ZZZZZZZZZZZZZZZZ$7
+Z$ZZZZZZZ$ZZZZ
    ?7ZZZZZ$
PACMAN
